<a href="https://colab.research.google.com/github/ritiy10/akriti_10/blob/main/My_first_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [17]:
import os
os.listdir('/content/drive/MyDrive')

['Colab Notebooks',
 'Cleaned_Students_Performance.csv',
 'Aadvika',
 'SAVE_20231023_140143.jpg',
 'SAVE_20231023_140134.jpg',
 'SAVE_20231023_140043.jpg',
 'SAVE_20231023_140022.jpg',
 'SAVE_20231023_135903.jpg',
 'SAVE_20231023_140000.jpg',
 'SAVE_20231023_135942.jpg',
 'SAVE_20231023_135931.jpg',
 'SAVE_20231023_135918.jpg',
 'SAVE_20231023_214754.jpg',
 'SAVE_20231023_211821.jpg',
 'SAVE_20231023_211802.jpg',
 '1629610488690.jpg',
 '2022-10-30-17-31-24-931.jpg',
 '2022-10-30-17-30-58-423.jpg',
 'payment recepit.jpg',
 'freshers',
 'VID-20230315-WA0015.mp4',
 '0d356dac714b434c9955c94c6789fbc6.mp4',
 'VID-20230313-WA0054.mp4',
 'VID-20230409-WA0003.mp4',
 'VID-20230314-WA0010.mp4',
 '9b251d630300457a99f6ab7f7a807974.mp4',
 'VID-20230409-WA0005.mp4',
 'a8f01cd0ccb246aaa741328e8f9974fc.mp4',
 '9a6c4548715b40e2ae58d866062bb600.mp4',
 'VID-20230409-WA0004.mp4',
 '2f10096f956645eb950e63952396090c.mp4',
 '6b9204b392c4436f86dddc31295e9e5e.mp4',
 'b3a4e8497a134ebb9d0e22614e3efd63.mp4',
 'b5dc4c0b069e4f45987bfff4429e30ff.mp4',
 '1a96819c0af240009814709215f7a3ad.mp4',
 'VID-20230312-WA0013 (1).mp4',
 'VID-20230312-WA0013.mp4',
 'VID-20230630-WA0005.mp4',
 'VID-20230630-WA0004.mp4',
 '970819306acc42ca9c5d93f27c32def0.mp4',
 'bd5ec22e9fe14ab68d7bfce520c0f25c.mp4',
 'VID-20230613-WA0056.mp4',
 'fc55766de16a428eaa849a0d316050a5.mp4',
 'VID-20230629-WA0000.mp4',
 'bd044b3c96ab4009abf2f5f43814cc31.mp4',
 '6ba9be31cef7400b96c1b46dfc7dcb1d.mp4',
 '5ea57263a24247e9910dba85695002ca.mp4',
 'VID-20230715-WA0016.mp4',
 'VID-20230715-WA0015.mp4',
 '99f196c751f84c1c96026a3b19039576.mp4',
 'Copy of IMG-20250406-WA0009.jpg',
 'basket.jpg',
 'assignment+1.f3z',
 'train_platform.py',
 'gender facemorphe.py',
 'Akriti_240082.gdoc',
 'Akriti_24.jpg',
 'IMG_20250718_203617.png',
 'Screenshot_20250729-184311.png',
 'Exam_Score_Prediction.csv']

In [20]:
import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/Exam_Score_Prediction.csv")
df.describe()

,student_id,age,study_hours,class_attendance,sleep_hours,exam_score
count,20000.000000,20000.000000,20000.000000,20000.000000,20000.00000,20000.000000
mean,10000.504600,20.473300,4.007604,70.017365,7.00856,62.513225
std,5773.654959,2.284458,2.308313,17.282262,1.73209,18.908491
min,1.000000,17.000000,0.080000,40.600000,4.10000,19.599000
25%,5000.750000,18.000000,2.000000,55.100000,5.50000,48.800000
50%,10000.500000,20.000000,4.040000,69.900000,7.00000,62.600000
75%,15000.250000,22.000000,6.000000,85.000000,8.50000,76.300000
max,20001.000000,24.000000,7.910000,99.400000,9.90000,100.000000

In [21]:
df.head()

,student_id,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score
0,1,17,male,diploma,2.78,92.9,yes,7.4,poor,coaching,low,hard,58.9
1,2,23,other,bca,3.37,64.8,yes,4.6,average,online videos,medium,moderate,54.8
2,3,22,male,b.sc,7.88,76.8,yes,8.5,poor,coaching,high,moderate,90.3
3,4,20,other,diploma,0.67,48.4,yes,5.8,average,online videos,low,moderate,29.7
4,5,20,female,diploma,0.89,71.6,yes,9.8,poor,coaching,low,moderate,43.7

In [33]:
import numpy as np
data=np.genfromtxt("/content/drive/MyDrive/Exam_Score_Prediction.csv",dtype=None, delimiter=',', skip_header=1, names=('student_id','age','gender','course','study_hour','class_attendance','internet_access','sleep_hour','sleep_quality','study_method','facility_rating','exam_difficulty','exam_score'))

In [30]:
data.shape

(20000,)

In [34]:
data

array([(    1, 17, 'male', 'diploma', 2.78, 92.9, 'yes', 7.4, 'poor', 'coaching', 'low', 'hard', 58.9),
       (    2, 23, 'other', 'bca', 3.37, 64.8, 'yes', 4.6, 'average', 'online videos', 'medium', 'moderate', 54.8),
       (    3, 22, 'male', 'b.sc', 7.88, 76.8, 'yes', 8.5, 'poor', 'coaching', 'high', 'moderate', 90.3),
       ...,
       (19999, 19, 'other', 'diploma', 7.88, 68.2, 'yes', 4.6, 'poor', 'group study', 'low', 'easy', 64.5),
       (20000, 19, 'male', 'bba', 4.6 , 76.3, 'no', 6.1, 'good', 'self-study', 'medium', 'moderate', 79. ),
       (20001, 20, 'male', 'b.sc', 7.5 , 47.9, 'yes', 7.5, 'poor', 'coaching', 'medium', 'moderate', 71. )],
      dtype=[('student_id', '<i8'), ('age', '<i8'), ('gender', '<U6'), ('course', '<U7'), ('study_hour', '<f8'), ('class_attendance', '<f8'), ('internet_access', '<U3'), ('sleep_hour', '<f8'), ('sleep_quality', '<U7'), ('study_method', '<U13'), ('facility_rating', '<U6'), ('exam_difficulty', '<U8'), ('exam_score', '<f8')])

In [44]:
data['exam_score']=(data['exam_score']/50)*100
data['exam_score']

array([58.9, 54.8, 90.3, ..., 64.5, 79. , 71. ])

In [39]:
print(data['class_attendance'])
len(data['class_attendance'])

[92.9 64.8 76.8 ... 68.2 76.3 47.9]

20000

In [48]:
print(data[data['class_attendance']>80]['exam_score'])
print(len(data[data['class_attendance']>80]['exam_score']))
print(data[data['class_attendance']>80]['exam_score'].mean())

[58.9 44.9 63.2 ... 56.7 95.  78.4]
6650
69.1942542857143

In [55]:
print(data[data['gender']=='female']['class_attendance'])
print(data[data['gender']=='female']['exam_score'])
print(len(data[data['gender']=='female']['exam_score']))
print(data[data['gender']=='female']['exam_score'].mean())

[71.6 69.  86.9 ... 96.1 66.3 73.3]
[43.7 53.7 63.2 ... 46.7 87.  93.9]
6579
62.58214500683995

In [75]:
import re
grades='ACAAAABCBCBAA'
print(re.findall("B",grades))
print(re.findall("[AB]",grades))
print(re.findall("[A][B-C]",grades))

print(re.findall("AB|AC",grades))
print(re.findall("[^A]",grades))
print(re.findall("^[^A]", grades))
print(re.findall("^[^B]", grades))

['B', 'B', 'B']
['A', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'A', 'A']
['AC', 'AB']
['AC', 'AB']
['C', 'B', 'C', 'B', 'C', 'B']
[]
['A']

In [85]:
print(re.findall("A{2,10}",grades))
print(re.findall("A{3,3}A{1,1}", grades))
print(re.findall("A{2,3}A{1,1}", grades))
print(re.findall("A{2,2}A{1,1}", grades))
print(re.findall("A{1,2}A{1,1}", grades))#B2B max 3A's to min 2A's
print(re.findall("A{1,1}A{1,1}", grades))#back-to-back 2A's

['AAAA', 'AA']
['AAAA']
['AAAA']
['AAA']
['AAA', 'AA']
['AA', 'AA', 'AA']

In [87]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive